---
# tasks file for user_firefox
- name: read Firefox ini file
  redhat_cop.fedora_desktop.configreader:
    path: "{{ user_firefox_profiles_ini }}"
  register: __user_firefox_profiles
- name: enumerate actual profiles
  ansible.builtin.include_tasks:
    file: profile.yml
  loop: "{{ __user_firefox_profiles.content | dict2items }}"
  loop_control:
    loop_var: profile_item
    label: "{{ profile_item.key }}"
  when:
    - profile_item.key is ansible.builtin.match('Profile[0-9][0-9]*')
    - profile_item.value['name'] is defined
    - >
      user_firefox_profiles == 'all'
      or (user_firefox_profiles == 'default' and 'default' in profile_item.value and profile_item.value['default'] == '1')
      or (profile_item.value['name'] == user_firefox_profiles)
