---
# tasks file for user_firefox
#- name: read Firefox ini file
#  debug:
#    msg: "{{ lookup('ansible.builtin.ini', 'Path', file=user_firefox_profiles_ini, section='Profile' + item|string, allow_no_value=True) }}"
#  loop: "{{ range(2) }}"
- name: read Firefox ini file
  redhat_cop.fedora_desktop.configreader:
    path: "{{ user_firefox_profiles_ini }}"
  register: __user_firefox_profiles
- name: enumerate actual profiles
  debug:
    msg: "{{ item.value['name'] }}"
  loop: "{{ __user_firefox_profiles.content | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - item.key is ansible.builtin.match('Profile[0-9][0-9]*')
    - item.value['name'] is defined
    - user_firefox_profiles == 'all' or (user_firefox_profiles == 'default' and 'default' in item.value and item.value['default'] == '1') or (item.value['name'] == user_firefox_profiles)
